trigger: none

pr: none

resources:
  pipelines:
  - pipeline: uhd_mono_pipeline
    source: 'uhddev mono pipeline'
    branch: master
  - pipeline: usrp-kas-pipeline
    source: 'usrp-kas'
    branch: zeus-ci
  repositories:
  - repository: meta-ettus
    type: github
    name: EttusResearch/meta-ettus-dev
    endpoint: EttusResearch
    ref: zeus-ci
  - repository: gr-ettus
    type: github
    name: EttusResearch/gr-ettusdev
    endpoint: EttusResearch
    ref: maint-3.8-uhd4.0
  - repository: ettus-rts
    type: github
    endpoint: EttusResearch
    name: EttusResearch/ettus-rts
    ref: master

stages:
- stage: test_uhd_embedded_stage
  displayName: Test Embedded UHD
  jobs:
  - template: templates/tests/job-uhd-x4xx-hardware-tests-sdr-test0.yml
    parameters:
      testOS: ubuntu1804
      uhdArtifactSource: uhd_mono_pipeline
  - template: templates/tests/job-uhd-x4xx-hardware-tests-pebbles.yml
    parameters:
      testOS: ubuntu1804
      uhdArtifactSource: uhd_mono_pipeline
